[package]
name = "heat-test"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"                                  # Parsing files
serde = { version = "1.0", features = ["derive"] }  # Easier deserilization
tokio = { version = "1.39", features = ["full"] } # Async runtime
